import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import AuthProvider from "@/app/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BlogifyHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white text-lg`}>
        <AuthProvider>
          <div className="container flex flex-col min-h-screen mx-auto px-5 sm:px-8 md:px-10">
            <Navbar />
            <div className="pt-16 md:pt-20">
              {children}
            </div>     
            <Footer />       
          </div>  
        </AuthProvider>   
      </body>
    </html>
  );
}
