import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BlogifyHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-bg text-text text-lg`}>
        <div className="container flex flex-col min-h-screen mx-auto px-5 sm:px-8 md:px-10">
          <Navbar />
          <div className="pt-16 md:pt-20">
            {children}
          </div>     
          <Footer />       
        </div>     
      </body>
    </html>
  );
}
